name = "nosana-fleet"
main = "src/index.js"
compatibility_date = "2024-01-01"
account_id = "020291db145b5daf09dc7d70eb53fafe"

[triggers]
crons = ["*/1 * * * *"]

[[kv_namespaces]]
binding = "FLEET_DATA"
id = "e0d07ab0a32a475983babf612dc5a6c4"

[[kv_namespaces]]
binding = "PUSH_SUBS"
id = "ab6a97a0f766496d8530c21e817ba5b0"
